title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-s25/team02-s25-07
owner: ucsb-cs156-s25
repo_name: team02-s25-07
pull_requests: [{"author":{"id":"U_kgDOB2-v9w","is_bot":false,"login":"hannyaYan","name":"hannYan"},"headRefName":"HY-MIR-e2e-tests","number":124,"title":"Hy mir e2e tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/124"},{"author":{"id":"U_kgDOB2-v9w","is_bot":false,"login":"hannyaYan","name":"hannYan"},"headRefName":"HY-MIR-integration-tests","number":123,"title":"Hy mir integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/123"},{"author":{"id":"U_kgDOB7-UXw","is_bot":false,"login":"zhushelly","name":"Shelly Zhu"},"headRefName":"sz-test","number":120,"title":"Sz - integration and end2end tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/120"},{"author":{"id":"MDQ6VXNlcjcwMzMwODU2","is_bot":false,"login":"acdamstedt","name":"Annika Damstedt"},"headRefName":"AD-HelpRequest-e2e","number":117,"title":"HelpRequest End to End","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/117"},{"author":{"id":"MDQ6VXNlcjcwMzMwODU2","is_bot":false,"login":"acdamstedt","name":"Annika Damstedt"},"headRefName":"AD-HelpRequest-integration","number":116,"title":"HelpRequest integration","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/116"}]
