title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-s25/team02-s25-07
owner: ucsb-cs156-s25
repo_name: team02-s25-07
pull_requests: [{"author":{"id":"U_kgDOB3D7gA","is_bot":false,"login":"linzezhou","name":"LINZE ZHOU"},"headRefName":"fz-e2e","number":113,"title":"Fz e2e","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/113"},{"author":{"id":"U_kgDOB3D7gA","is_bot":false,"login":"linzezhou","name":"LINZE ZHOU"},"headRefName":"fz-integration","number":112,"title":"Fz integration","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/112"},{"author":{"id":"U_kgDOB2-uaQ","is_bot":false,"login":"stevenliu2002","name":"Yuchen Liu"},"headRefName":"sl-rec-e2e-tests","number":111,"title":"Sl rec e2e tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/111"},{"author":{"id":"U_kgDOB2-uaQ","is_bot":false,"login":"stevenliu2002","name":"Yuchen Liu"},"headRefName":"sl-rec-integration-tests","number":108,"title":"Sl rec integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/108"}]
