
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-07
owner: ucsb-cs156-s25
repo_name: team02-s25-07
pull_requests: [{"author":{"id":"MDQ6VXNlcjcwMzMwODU2","is_bot":false,"login":"acdamstedt","name":"Annika Damstedt"},"headRefName":"AD-HelpRequest-create-page","number":90,"title":"AD -  Create Page for HelpRequest plus tests and stories","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/90"},{"author":{"id":"U_kgDOB7-UXw","is_bot":false,"login":"zhushelly","name":"Shelly Zhu"},"headRefName":"shelly-articles","number":89,"title":"table component for articles and placeholder files -sz","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/89"},{"author":{"id":"U_kgDOB2-uaQ","is_bot":false,"login":"stevenliu2002","name":"Yuchen Liu"},"headRefName":"sl-create-rec-page","number":84,"title":"Sl create rec page","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/84"}]
