
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-07
owner: ucsb-cs156-s25
repo_name: team02-s25-07
pull_requests: [{"author":{"id":"U_kgDOB7-UXw","is_bot":false,"login":"zhushelly","name":"Shelly Zhu"},"headRefName":"sz-articles-edit","number":99,"title":"Sz - articles edit page","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/99"},{"author":{"id":"U_kgDOB7-UXw","is_bot":false,"login":"zhushelly","name":"Shelly Zhu"},"headRefName":"sz-articles-index","number":98,"title":"Sz - articles index page ","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/98"},{"author":{"id":"U_kgDOB7-UXw","is_bot":false,"login":"zhushelly","name":"Shelly Zhu"},"headRefName":"shelly-articles","number":97,"title":"create Articles page","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/97"},{"author":{"id":"MDQ6VXNlcjg1OTgwOTEz","is_bot":false,"login":"hannahz0","name":"Hannah Zhang"},"headRefName":"hz-ucsborg-index-page","number":96,"title":"hz - Index Page for UCSBOrganization plus tests and stories","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/96"},{"author":{"id":"U_kgDOB3D7gA","is_bot":false,"login":"linzezhou","name":"LINZE ZHOU"},"headRefName":"fz-edit-page","number":95,"title":"fz - add edit and test","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/95"},{"author":{"id":"MDQ6VXNlcjcwMzMwODU2","is_bot":false,"login":"acdamstedt","name":"Annika Damstedt"},"headRefName":"AD-HelpRequest-index-page","number":93,"title":"AD - Index page for HelpRequest plus tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/93"}]
