
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-07
owner: ucsb-cs156-s25
repo_name: team02-s25-07
pull_requests: [{"author":{"id":"U_kgDOB2-uaQ","is_bot":false,"login":"stevenliu2002","name":"Yuchen Liu"},"headRefName":"ls-rec-placeholder-pages","number":80,"title":"sl - add placeholder pages for Index, Edit, Create for RecommendationRequest","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/80"},{"author":{"id":"U_kgDOB7-UXw","is_bot":false,"login":"zhushelly","name":"Shelly Zhu"},"headRefName":"shelly-articles","number":78,"title":"create form component","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/78"},{"author":{"id":"U_kgDOB2-uaQ","is_bot":false,"login":"stevenliu2002","name":"Yuchen Liu"},"headRefName":"sl-rec-table","number":77,"title":"sl - add RecommendationRequestTable, tests and Util tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/77"},{"author":{"id":"MDQ6VXNlcjg1OTgwOTEz","is_bot":false,"login":"hannahz0","name":"Hannah Zhang"},"headRefName":"hz-UCSBOrganization-placeholders","number":75,"title":"hz - Copy Placeholders for UCSBOrganization pages","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/75"}]
