
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-07
owner: ucsb-cs156-s25
repo_name: team02-s25-07
pull_requests: [{"author":{"id":"MDQ6VXNlcjg1OTgwOTEz","is_bot":false,"login":"hannahz0","name":"Hannah Zhang"},"headRefName":"hz-UCSBOrganization-placeholders","number":75,"title":"hz - Copy Placeholders for UCSBOrganization pages","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/75"},{"author":{"id":"U_kgDOB2-uaQ","is_bot":false,"login":"stevenliu2002","name":"Yuchen Liu"},"headRefName":"sl-rec-form","number":74,"title":"sl - add RecommendationRequestForm and tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/74"},{"author":{"id":"U_kgDOB3D7gA","is_bot":false,"login":"linzezhou","name":"LINZE ZHOU"},"headRefName":"fz-item-fixtures","number":73,"title":"fz - added fixtures for menu items","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/73"},{"author":{"id":"U_kgDOB2-v9w","is_bot":false,"login":"hannyaYan","name":"hannYan"},"headRefName":"HY-MIR-table","number":71,"title":"HY - add table and tests for MIR","url":"https://github.com/ucsb-cs156-s25/team02-s25-07/pull/71"}]
